[package]
name = "phcue-qc"
version = "0.3.0"
edition = "2018"

[dependencies]
fastq = "*"
num-format = "*"
dashmap = "*"
hdrhistogram = "*"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
clap = { version = "3.2.10", features = ["derive"] }
find_peaks = "0.1.5"
